version: "3.9"
services:
  backend:
    depends_on:
      - frontend
    build: ./backend/src
    container_name: backend
    ports:
      - "9001:5000"
    volumes:
      - /app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - /app

#To make changes must delete dsa3101-2210-13-lta_web1/dsa3101-2210-13-lta_web2 under images
